on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '01 12 * * *'

jobs:
  url_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://holy-bush-484.fly.dev/
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
      - name: Check the deployed service URL (should fail)
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://holy-bush-485.fly.dev/
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
